config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")

  # get "/appointments", to: "appointments#index" 
  # get "/appointments/:id", to: "appointments#show"
  
  root "appointments#index"

  resources :appointments do
    resources :comments, :prescriptions
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  include Visible
  
  has_many :comments, dependent: :destroy
  has_many :prescriptions
  
  validates :patient_name, presence: true
  validates :date, presence: true
  validates :time, presence: true
  validates :issue, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :appointment

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  def archived?
    status == 'archived'
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end
  
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :appointment
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :appointment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  http_basic_authenticate_with name: "user1", password: "secret", except: [:index, :show]

  def index
    @appointments = Appointment.all
  end

  def show 
    @appointment = Appointment.find(params[:id]) 
  end

  def new 
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      redirect_to @appointment
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to @appointment
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to root_path, status: :see_other
  end

  private
    def appointment_params
      params.require(:appointment).permit(:patient_name, :date, :time, :issue, :status)
    end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  http_basic_authenticate_with name: "user1", password: "secret", only: :destroy

  def create
    @appointment = Appointment.find(params[:appointment_id])
    @comment = @appointment.comments.create(comment_params)
    redirect_to appointment_path(@appointment)
  end

  def destroy
    @appointment = Appointment.find(params[:appointment_id])
    @comment = @appointment.comments.find(params[:id])
    @comment.destroy
    redirect_to appointment_path(@appointment), status: 303
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end

end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  
  def create
    @appointment = Appointment.find(params[:appointment_id])
    @prescription = @appointment.prescriptions.create(prescription_params)
    redirect_to appointment_path(@appointment)
  end

  private
    def prescription_params
      params.require(:prescription).permit(:drug, :amount)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/appointments/_form.html.erb
<%= form_with model: appointment do |form| %>

  <div>
    <%= form.label :date %><br>
    <%= form.text_field :date %>
    <% appointment.errors.full_messages_for(:date).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :time %><br>
    <%= form.text_field :time %>
    <% appointment.errors.full_messages_for(:time).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :patient_name %><br>
    <%= form.text_field :patient_name %>
    <% appointment.errors.full_messages_for(:patient_name).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :issue %><br>
    <%= form.text_area :issue %>
    <% appointment.errors.full_messages_for(:issue).each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/appointments/edit.html.erb
<h1>Edit appointment</h1>

<%= render "form", appointment: @appointment %>

app/views/appointments/index.html.erb
<h1>Scheduler</h1>

<p>Number of appointments: <%= Appointment.public_count %></p>

<ul>
  <% @appointments.each do |appointment| %>
    <% unless appointment.archived? %>
      <li>
        <%= link_to appointment.time, appointment %>
      </li>
    <% end %>
  <% end %>
</ul>


<%= link_to "New Appointment", new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render "form", appointment: @appointment %>

app/views/appointments/show.html.erb
<h1><%= @appointment.patient_name %></h1>

<p><%= @appointment.issue %></p>

<ul>
  <li><%= link_to "Edit", edit_appointment_path(@appointment) %></li>
    <li><%= link_to "Destroy", appointment_path(@appointment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li>
</ul>


<h2>Comments</h2>
<%= render @appointment.comments %>


<h2>Add comment</h2>
<%= render 'comments/form' %>

<h2>Prescription</h2>
<%= render @appointment.prescriptions %>

<h2>Add a prescription:</h2>
<%= render 'prescriptions/form' %>

<div>
  <a href="/">Home</a>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<p>
  <%= link_to "Destroy Comment", [comment.appointment, comment], 
      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [@appointment, @appointment.comments.build] do |form| %>

  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prescriptions/_form.html.erb
<%= form_with model: [ @appointment, @appointment.prescriptions.build ] do |form| %>
  <p>
    <%= form.label :drug %><br>
    <%= form.text_field :drug %>
  </p>
  <p>
    <%= form.label :amount %><br>
    <%= form.text_area :amount %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/prescriptions/_prescription.html.erb
<p>
  <strong>Drug:</strong>
  <%= prescription.drug %>
</p>

<p>
  <strong>Amount:</strong>
  <%= prescription.amount %>
</p>